//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCA_WEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBLCAConf : DbContext
    {
        public DBLCAConf()
            : base("name=DBLCAConf")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProduktTyp> ProduktTyps { get; set; }
        public virtual DbSet<Rohstoff> Rohstoffs { get; set; }
        public virtual DbSet<Umweltindikator> Umweltindikators { get; set; }
        public virtual DbSet<EndOfLifeData> EndOfLifeDatas { get; set; }
        public virtual DbSet<ProduktRohstoffUmweltindikator> ProduktRohstoffUmweltindikators { get; set; }
    }
}
