//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndOfLifeData
    {
        public int Produkt_Id { get; set; }
        public int Rohstoff_Id { get; set; }
        public Nullable<decimal> Recyclingfaehig { get; set; }
        public Nullable<decimal> Entsorgungskosten { get; set; }
        public Nullable<decimal> Recyclingerloese { get; set; }
        public Nullable<decimal> WeiterverkaufPM { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Rohstoff Rohstoff { get; set; }
    }
}
