//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduktRohstoffUmweltindikator
    {
        public int Produkt_Id { get; set; }
        public int Rohstoff_Id { get; set; }
        public int Umweltindikator_Id { get; set; }
        public int Phase { get; set; }
        public Nullable<decimal> Rohstoff_Menge_in_t { get; set; }
        public Nullable<decimal> Umweltindikator_Menge { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Rohstoff Rohstoff { get; set; }
        public virtual Umweltindikator Umweltindikator { get; set; }
    }
}
