//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.EndOfLifeDatas = new HashSet<EndOfLifeData>();
            this.ProduktRohstoffUmweltindikators = new HashSet<ProduktRohstoffUmweltindikator>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Menge { get; set; }
        public Nullable<double> Nutzungsdauer_in_Jahre { get; set; }
        public Nullable<double> Gesamtgewicht { get; set; }
        public Nullable<double> Energieverbrauch_in_GJ { get; set; }
        public Nullable<double> CO2Ausstoss_t_a { get; set; }
        public Nullable<decimal> Energiekosten_pro_GJ { get; set; }
        public Nullable<decimal> ProduktionsmittelKosten { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public System.DateTime DateOfChanging { get; set; }
        public string CreatedBy { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<int> Typ_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EndOfLifeData> EndOfLifeDatas { get; set; }
        public virtual ProduktTyp ProduktTyp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduktRohstoffUmweltindikator> ProduktRohstoffUmweltindikators { get; set; }
    }
}
