//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProduktRohstoffUmweltindikators = new HashSet<ProduktRohstoffUmweltindikator>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Menge { get; set; }
        public Nullable<double> Nutzungsdauer_in_Jahre { get; set; }
        public Nullable<double> Gesamtgewicht { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public System.DateTime DateOfChanging { get; set; }
        public string CreatedBy { get; set; }
        public string ChangeBy { get; set; }
        public Nullable<int> Typ_Id { get; set; }
    
        public virtual ProduktTyp ProduktTyp { get; set; }
        public virtual ICollection<ProduktRohstoffUmweltindikator> ProduktRohstoffUmweltindikators { get; set; }
    }
}
