//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produktionsmittel_DeutscheBahn
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Rohstoff_Typ_1 { get; set; }
        public int Rohstoff_Typ_2 { get; set; }
        public int Rohstoff_Typ_3 { get; set; }
        public int Rohstoff_Typ_4 { get; set; }
    
        public virtual Rohstoff Rohstoff { get; set; }
        public virtual Rohstoff Rohstoff1 { get; set; }
        public virtual Rohstoff Rohstoff2 { get; set; }
        public virtual Rohstoff Rohstoff3 { get; set; }
    }
}
