//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rohstoff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rohstoff()
        {
            this.Produktionsmittel_DeutscheBahn = new HashSet<Produktionsmittel_DeutscheBahn>();
            this.Produktionsmittel_DeutscheBahn1 = new HashSet<Produktionsmittel_DeutscheBahn>();
            this.Produktionsmittel_DeutscheBahn2 = new HashSet<Produktionsmittel_DeutscheBahn>();
            this.Produktionsmittel_DeutscheBahn3 = new HashSet<Produktionsmittel_DeutscheBahn>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Menge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produktionsmittel_DeutscheBahn> Produktionsmittel_DeutscheBahn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produktionsmittel_DeutscheBahn> Produktionsmittel_DeutscheBahn1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produktionsmittel_DeutscheBahn> Produktionsmittel_DeutscheBahn2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produktionsmittel_DeutscheBahn> Produktionsmittel_DeutscheBahn3 { get; set; }
    }
}
